### ISSUE TITLE
Social Media Icons in About Us Section Not Linked to Handles

### ISSUE THREAD

**Issue by Apurv7777** [juhinagpure/Eduford-university#1]
**Description**: The social media icons in the "About Us" section of our app/webpage are currently not linked to their respective social media handles. This prevents users from easily accessing our social media profiles.  

**Steps to Reproduce:**
1)  Navigate to the "About Us" section. 
2) Locate the social media icons (e.g., Facebook, Twitter, Instagram). 
3) Click on any of the icons. 

**Expected Behavior:** 
Clicking on a social media icon should redirect users to the respective social media handle.

**Actual Behavior:** 
Clicking on any social media icon does not redirect users. 

**Additional Information:** 
This issue impacts user engagement and brand visibility. It's crucial to ensure that users can easily connect with us on social media platforms. We need to update the links associated with each icon to direct users to the correct social media handles.  

**Assignees**: Assign me this issue.

**Labels**: bug, enhancement  

**Priority**: High

**Comment by ranasuryansh14** [comment]
Assign me this issue.

**Comment by kamalesh-og** [comment]
Hi,
I'm one of the contributors for the GSOCC'24, I would love to take up this issue and work on this UI and element functionality.
I have experience in Web Design and working with this functionality and I can assure you that I can work on this navigation part of social media icons on the "About Us" page.
Can you please assign this issue to me
Thank you!

**Comment by Abhinavpatra** [comment]
hey Apurv, i have already started working on this issue, let me know if you can assign me this issue, under gssoc'24.

**Comment by Jithendranath8** [comment]
hello @Apurv7777 , I have experience in solving this issue and making it responsive , I have set it in my local setup and done changes on it . Please assign me this issue

**Comment by Gokilp** [comment]
Assign this issue to me under GSSoc'24 so that i can work on it

**Comment by kanikaa-3018** [comment]
please assign this issue to me for GSSoc'24. ( none of the footers are linked along with the UI of the section, a separate QnA section can be added in footer section)

**Comment by anirudh-why** [comment]
Please assign me this issue under GSSOC'24

**Comment by ankurpunia30** [comment]
hey @Apurv7777,ankur this side I have already completed the setup looking forward to the assignment of issues under GSSoc'24 please provide the links that are needed to be connected, it is not just about sections most of the footer requires these links

**Comment by Gokilp** [comment]
Assinged any one working on issue

**Comment by Gokilp** [comment]
Any one working the issue

**Comment by Gokilp** [comment]
@juhinagpure  Please review my PR

**Comment by amitkumar2308** [comment]
hey! I am Amit I am pretty good at web dev things so can i resolve this issue..................

**Comment by paridhi1509** [comment]
Please assign this issue to me

**Comment by Abhinavpatra** [comment]
I have already resolved this issue  2 days ago, i will send another PR.you may view and check it again.
