### ISSUE TITLE
Website header logo

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [juhinagpure/Eduford-university#100]
![image](https://github.com/juhinagpure/Eduford-university/assets/125277258/6212a072-8224-4aed-80e0-6eb9cc0d20ad)

add here a website logo for better user experience

**Comment by Dishika-Akhare** [comment]
I would like to add Logo to the website @juhinagpure can you please assign me this issue under GSSOC'24. I know how to add logo to the website.

**Comment by aasthabagrawal** [comment]
Hey!
Please assign this task to me because I have prior experience to this.

**Comment by RamakrushnaBiswal** [comment]
@juhinagpure mam please review the PR and add some label
