### ISSUE TITLE
Footer can make more creative 

### ISSUE THREAD

**Issue by deepeshmlgupta** [juhinagpure/Eduford-university#115]
Assign me this issue I will make the footer more attractive. So, please assign me this issue under gssoc'24

**Comment by technicalkuldeep** [comment]
Footer is not good , it can be more attractive , I am very very good in HTML and CSS so I request you to kindly assign me this issue . I am giving you the surety that the footer will look much more attractive that as of now

**Comment by spacedust26** [comment]
Hey @juhinagpure ! Could you please assign this issue to me under Gssoc'24. I'd like to come with a better footer design. Thank you !

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
