### ISSUE TITLE
Add a sticky navbar and improve the UI and user experience 

### ISSUE THREAD

**Issue by parikhitritgithub** [juhinagpure/Eduford-university#13]
I just watched your website. When I scroll down, it's very difficult for me to go back to the home page so  basically it's hard to navigate  . for better user experience  I can improve your UI by adding a sticky navbar also  i want to improve  your text-font  . 

Assign me this issue.

**Comment by yashisrani** [comment]
@juhinagpure kindly assign me this issue under #gssoc'24 .. I will Enhance UI of navbar and make it sticky and responsive..

**Comment by parikhitritgithub** [comment]
Hello @juhinagpure Kindly assign this issue to me,  because I find the issue.

**Comment by GarimaSingh0109** [comment]
Hello @juhinagpure Kindly assign this issue to me, under #gssoc'24 i am willing to improve the the navbar UI UX

**Comment by PoojaGadagi08** [comment]
Hello @juhinagpure  mam
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by ankitsinghbisht8** [comment]
I'm eager to tackle this issue. Please assign it to me.

**Comment by Adi-gitX** [comment]
I'm interested in working on a task that involves adding a sticky navigation bar and improving the UI and user experience. The task, labeled as #13, requires me to implement a sticky navigation bar using CSS or JavaScript to enhance navigation and improve the user experience. Additionally, I'll conduct a UI audit to identify areas for improvement and make necessary refinements to improve the overall aesthetics and usability of the design. I plan to start by implementing the sticky navbar functionality and then proceed to conduct the UI audit to optimize the user experience.

please assign me this issue

**Comment by bk408** [comment]
Hello @juhinagpure 
I'm proposing an update to the navbar sticky and design to enhance its aesthetics and usability. This update will include improvements in colour scheme, typography, layout, and responsiveness.

**Comment by GarimaSingh0109** [comment]
@juhinagpure Can you please add gssoc'24 & level lable to the pr & the issue
