### ISSUE TITLE
No icon in TitleBar

### ISSUE THREAD

**Issue by SrijaVuppala295** [juhinagpure/Eduford-university#145]
There is no icon in titlebar !!

![Screenshot 2024-05-17 001531](https://github.com/juhinagpure/Eduford-university/assets/140592148/98d0ad83-a466-4588-89de-8b4d9d334550)

Please assign this issue to me..

**Comment by roushanverma23** [comment]
@juhinagpure please assign this task, I want to work on this
![gssoc](https://github.com/GameSphere-MultiPlayer/Squard-line/assets/137530796/bc19c5b1-a3c9-457f-b0f4-09e916b6b627)

**Comment by AnirbanChattopadhyay-2004** [comment]
please assign this issue to me I can make changes in it

**Comment by toodiv** [comment]
I can contribute to the issue with a clean and efficient code. Kindly accept my issue under GSSOC'24.
