### ISSUE TITLE
Navbar is not in the proper format for many pages..

### ISSUE THREAD

**Issue by SrijaVuppala295** [juhinagpure/Eduford-university#146]
The navbar is not in the proper format for many pages .Please assign this issue to me..

![Screenshot 2024-05-17 001950](https://github.com/juhinagpure/Eduford-university/assets/140592148/9d4cec34-92a7-401e-8e78-63f068545022)

**Comment by r7projects-shayan** [comment]
@juhinagpure kindly assign me this issue. I will fix it in a short amount of time

**Comment by DevNandini02** [comment]
@juhinagpure please assign this issue to me also. And please add the gssoc label.

**Comment by r7projects-shayan** [comment]
@juhinagpure I have created two pull requests, the first one #187 is for the master branch and #188 is for the main branch. If one of them doesn't get merged you can merge the other one. Thanks
