### ISSUE TITLE
Add theme switching: darkmode and light mode

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [juhinagpure/Eduford-university#20]

**Comment by DharshiBalasubramaniyam** [comment]
@juhinagpure please assign this issue to me.

**Comment by PoojaGadagi08** [comment]
Hello @juhinagpure  mam
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by rohhitsingh19** [comment]
Hello @juhinagpure,

I have the relevant skills required to modify the theme and can add new features to enhance the website's effectiveness. As a contributor in GSSOC, I would appreciate if you could assign this project to me.

Thank you.

**Comment by parikhitritgithub** [comment]
Hello @juhinagpure
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by Abhishek-0899** [comment]
Please assign this issue to me under gssoc'24

**Comment by Varda003** [comment]
please assign this issue to me gssoc'24 . I am well experienced in MERN stack.

**Comment by MonikaLuhach** [comment]
Hii, I'm happy to work on this issue under GSsoc'24 contribution. Could you please assign it to me?

**Comment by vignesh-0512** [comment]
Hello @juhinagpure as a gssoc'24 contributor, and also i have good experience in html, css, js so i believe that i am good enough to work on this issue so i request you to assign me this issue.

**Comment by varun1903** [comment]
Nameste @juhinagpure Please assign this issue to me under gssoc'24

**Comment by Paavni-Goyal** [comment]
Hi, @juhinagpure I think I'm qualified to work on this problem because I'm a gssoc'24 contributor and have solid html, css, and js knowledge. Please assign me this issue.
