### ISSUE TITLE
Add a Mini Chatbot

### ISSUE THREAD

**Issue by AsmitaMishra24** [juhinagpure/Eduford-university#263]
Description:
Integrate a mini chatbot on our webpage to enhance user interaction and provide quick support.

Requirements:

Design and Appearance:
Minimalistic, user-friendly design.
Appears as a small icon in the bottom right corner.
Expands into a chat window upon clicking.

Functionality:
Handles common questions about our services.
Provides predefined responses for FAQs.
Option to escalate to a human representative.
Supports text input and displays text responses.

**Comment by AsmitaMishra24** [comment]
I would like to address this issue as part of GSSOC'24. Please assign it to me.

**Comment by meenakshiiyer2531** [comment]
Can this issue be assigned to me along with @AsmitaMishra24 for gssoc '24
