### ISSUE TITLE
Would like to add custom cursor and scroll bar

### ISSUE THREAD

**Issue by Anjaliavv51** [juhinagpure/Eduford-university#287]
Custom cursor to pointer and scroll bar.

![Screenshot 2024-06-01 172517](https://github.com/juhinagpure/Eduford-university/assets/154777864/2af3a62c-8270-4752-a434-dd67b14d6e02)

![Screenshot 2024-06-01 172900](https://github.com/juhinagpure/Eduford-university/assets/154777864/3a51366a-08de-4cc7-ab08-e0e45f881f58)

Please assign under GSSOC.

**Comment by SCR01** [comment]
I can solve this issue; can you assign me?

**Comment by Shilpajha29** [comment]
assign this task to me
