### ISSUE TITLE
Add a preloader 

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [juhinagpure/Eduford-university#33]
Hi @juhinagpure,  please assign this issue to me under gssoc 24

**Comment by bhavanishanker-png** [comment]
Please allocate this task to me. I'm capable of tackling it as I possess all the requisite skills to address the matter at hand.

**Comment by ayush-kumarrai** [comment]
Hello @juhinagpure  sir. Hope you are well. I am ready to add a preloader to your website and I'll be thankful to you if you assign me this task. Thanks.
