### ISSUE TITLE
Updating readme.md file

### ISSUE THREAD

**Issue by kanishk-2** [juhinagpure/Eduford-university#335]
<img width="850" alt="1" src="https://github.com/juhinagpure/Eduford-university/assets/157130879/878f8e01-e5e6-40a4-8996-cfa2b610f597">

After cloning next step should be navigating to that folder and then next step should ne rpm install.
Eg - cd Eduford-university

**Comment by muskan191103** [comment]
I would like to fix this issue
I am a GSSoC'24 contributor
Please assign this issue to me.

**Comment by 143divya** [comment]
Can you please assign this issue to me under Gssoc24? I want to work on this.
