### ISSUE TITLE
Twitter logo change to updatex version X.

### ISSUE THREAD

**Issue by PrashantAnand03** [juhinagpure/Eduford-university#348]
your project twitter logo is outdated upgrade with updated version X.

![Edu-ss](https://github.com/user-attachments/assets/ba70e5dd-3ca1-4c85-a5d0-1f40f6e0a6de)

**Comment by PrashantAnand03** [comment]
I would like to work on this issue. Please assign me to this issue and label it under GSSoc '24. Also, label its category as (level 1, 2, 3). I have implemented the same change in my recent project, so I could easily fix this bug.

**Comment by shaina123786** [comment]
I want add some hover effect on social media icons . So , Please assign it to me.
