### ISSUE TITLE
add hover effects for Our features page 

### ISSUE THREAD

**Issue by kairveeehh** [juhinagpure/Eduford-university#5]
would like to improve the UI here , 
## please assign this issue to me under gssoc'24 as I have already cloned the repo

**Comment by Gokilp** [comment]
Assign this issue to me under GSSoc'24 so that i can work on it 
]

**Comment by Shyambarua** [comment]
Assign this Issue to me

**Comment by Dev-AyushTrivedi** [comment]
I am interested in working on this issue. Could you please assign it to me? I am participating in  
GSSoC 2024 and would love to contribute to this project.

**Comment by anirudh-why** [comment]
Please assign me this issue under GSSOC'24

**Comment by Abhinavagarwa** [comment]
Assign this issue to me under GSSoc'24 so that i can work on it

**Comment by ishaa18** [comment]
I would like to work on these issue. As a gssoc 24 contibutor I'm asking to allow me to work on these issue.

**Comment by Gokilp** [comment]
im started working the issue why unassign to me ?

**Comment by hussain123sahil** [comment]
Please assign me this issue.

**Comment by Gokilp** [comment]
please review my pr @juhinagpure

**Comment by MonikaLuhach** [comment]
Hii, I would like to work on this issue under GSsoc'24 contribution. Could you please assign it to me?

**Comment by Gokilp** [comment]
please review my PR @juhinagpure

**Comment by Dev-AyushTrivedi** [comment]
Dear Repository Admin,
I hope this message finds you well. I am writing to request the addition of the 'gssoc' label to this repository. This label would be very helpful for organizing issues and pull requests related to the GirlScript Summer of Code (GSSOC).

**Comment by paridhi1509** [comment]
Please assign this issue to me under GSSoC'24
