### ISSUE TITLE
User name is not Saving

### ISSUE THREAD

**Issue by Madhu-mac** [juhinagpure/Eduford-university#67]
In the settings page we can't able to save the changes for the username. And there is no dialogue box showing up to indicate that the changes are saved or not. 

Here's the video of detailed view how to see this bug:

https://github.com/digitomize/digitomize/assets/88281761/347d3c3f-96b6-4755-89e2-894400826cf1

**Comment by Manaswini123456** [comment]
Hello, I am a full stack developer with the required tech stack, kindly assign me with this issue under GSSOC'24 so that I can provide my insights and solutions.
