### ISSUE TITLE
Spacing in the my facilities section

### ISSUE THREAD

**Issue by anshulsoni4** [juhinagpure/Eduford-university#73]
![image](https://github.com/juhinagpure/Eduford-university/assets/74638335/c5a3c0cb-93c9-4be4-9b36-b544b8511c63)
 
 
will make the styling changes

**Comment by Sujitmaurya123** [comment]
@anshulsoni4 please assign me this issues

**Comment by technicalkuldeep** [comment]
@anshulsoni4 I am very good in HTML and CSS , 
So please assign me this issue 
I will gonna solve it as quick as possible in a beautiful way
